#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Check if the meloday.py file exists in /app, and copy it from /meloday if it doesn't
if [[ ! -f /app/meloday.py ]]; then
    cp /meloday/meloday.py /app/meloday.py
    chmod +x /app/meloday.py
fi

# Ensure moodmap.json exists in /app; copy it from /meloday/assets if missing
if [[ ! -f /app/moodmap.json ]]; then
    ln -s /config/assets/moodmap.json /app/moodmap.json
fi

# Check if the assets directory symlink exists in /app, and create it if it doesn't
if [[ ! -d /app/assets/ ]]; then
    ln -s /config/assets /app/assets
fi

# Check if the config.yml symlink exists in /app, and create it if it doesn't
if [[ ! -f /app/config.yml ]]; then
    ln -s /config/config.yml /app/config.yml
fi
