#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Check if the config file exists, and copy it if it doesn't
if [[ ! -f /config/config.yml ]]; then
    cp /meloday/config.yml /config/config.yml
fi

# Check if the assets directory exists, and copy it if it doesn't
if [[ ! -d /config/assets/ ]]; then
    cp -r /meloday/assets/ /config/assets/
fi

# Set permissions
lsiown -R abc:abc \
    /config