#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ ! -f /config/config.yml ]]; then
    cp /meloday/config.yml /config/config.yml
fi

if [[ ! -f /config/assets/ ]]; then
    cp -r /meloday/assets/ /config/assets/
fi

# permissions
lsiown -R abc:abc \
    /config