#!/usr/bin/with-contenv bash
### Default values
sleepInterval='1m'

echo "Running meloday..."
# run py script
if ! python /app/meloday.py -c; then
  echo "Error: meloday.py failed to execute." >&2
  exit 1
fi

echo "Meloday run Complete. Sleeping for ${sleepInterval}."
sleep ${sleepInterval}
